### ISSUE TITLE
CI for beamlines is a bit limp

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/bl38p#14]
- first the CI only loads each IOC with minimal config to verify it loads
- second there is no need for CI to complete before a release is made because `ec ioc deploy` gets assets direct from the tagged repo.

For the first my excuse is 'one day we will have a Tickit sim for all beamline devices and the CI will system test each IOC Instance'

For the second we *could* put the beamline chart and ioc folders into release assets and have  `ec ioc deploy` pull them from there. Then you would have to wait for build success before you could deploy a versioned IOC.

*BUT* that seems a little masochistic to me - I kinda like the speed of versioned IOC deploy and the REAL test always comes on the beamline anyway.

@coretl any thoughts on this?

**Comment by coretl** [comment]
I think we should leave it like it is. When we add a Tickit sim then we will have greater confidence that pre-shutdown changes will work, but we don't want to wait for those tests to run as they are potentially quite lengthy

**Comment by gilesknap** [comment]
This is now much improved. It checks the instance schemas and that versions of schema and generic IOC match.
